version: '3'

networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable
      PORT: ${APP_PORT}
      TZ: "Asia/Jakarta"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  
  db:
    platform: linux/x86_64
    image: postgres:alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Asia/Jakarta"
    ports:
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

volumes:
  db:
    driver: local
